### ISSUE TITLE
TriggerClause changes in level source do not force reload.

### ISSUE THREAD

**Issue by GoogleFrog** [HourglassGame/HourglassII#9]
The TriggerClause is not in the comparator for checking whether a level needs to be reloaded from the source files. This causes confusing trigger clause 'bugs' when making levels. I was not able to get the comparator working when I initially implemented it.

**Comment by Mankarse** [comment]
I believe this was fixed by https://github.com/HourglassGame/HourglassII/commit/86b9a9aa2e89c08ec185b83125cc298f07e87e1c
